apiVersion: v1
kind: Service
metadata:
  name: db
  labels: 
    name: db
    app: postgres-service
spec:
  ports:
    - port: 5432
      target-port: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app