apiVersion: v1
kind: Deployment
metadate:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: demo-voting-app
spec:
  replicas:
  selector:
    matchlabels:
      name: voting-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: voting-app  
        image: kodecloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80