apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels: 
    name: voting
    app: demo-voting-service
spec:
  type: NodePort
  ports:
    - port: 80
      target-port: 80
      nodePort: 30005
  selector:
    name: voting
    app: demo-voting-service