apiVersion: v1
kind: Pod
metadate:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: worker-app
    image: kodecloud/examplevotingapp_worker:v1
    ports:
      - containerPort: 6379